module.exports = {
    ageInfo: [{ 'code': '1', 'name': '\u513f\u7ae5', 'englishName': 'child' }, { 'code': '2', 'name': '\u5c11\u5e74', 'englishName': 'young-aged' }, { 'code': '3', 'name': '\u9752\u5e74', 'englishName': 'youth' }, { 'code': '4', 'name': '\u4e2d\u5e74', 'englishName': 'middle-aged' }, { 'code': '5', 'name': '\u8001\u5e74', 'englishName': 'old-aged' }, { 'code': '0', 'name': '\u672a\u77e5', 'englishName': 'uncertain' }],
    beardInfo: [{ 'code': '1', 'name': '\u65e0\u80e1\u987b' }, { 'code': '2', 'name': '\u6709\u80e1\u987b' }, { 'code': '0', 'name': '\u672a\u77e5' }],
    expressionInfo: [{ 'code': '0', 'name': '\u672a\u77e5' }],
    glassesInfo: [{ 'code': '0', 'name': '\u672a\u77e5' }, { 'code': '1', 'name': '\u672a\u6234\u773c\u955c' }, { 'code': '2', 'name': '\u6234\u773c\u955c' }],
    hairInfo: [{ 'code': '1', 'name': '\u957f\u53d1' }, { 'code': '2', 'name': '\u77ed\u53d1' }, { 'code': '3', 'name': '\u5149\u5934' }, { 'code': '4', 'name': '\u76d8\u53d1' }, { 'code': '5', 'name': '\u9a6c\u5c3e' }, { 'code': '0', 'name': '\u672a\u77e5' }],
    maskInfo: [{ 'code': '0', 'name': '\u672a\u77e5' }, { 'code': '1', 'name': '\u672a\u6234\u53e3\u7f69' }, { 'code': '2', 'name': '\u6234\u53e3\u7f69' }],
    orientInfo: [{ 'code': '1', 'name': '\u524d' }, { 'code': '2', 'name': '\u540e' }, { 'code': '3', 'name': '\u4fa7' }, { 'code': '0', 'name': '\u672a\u77e5' }],
    raceInfo: [{ 'code': '1', 'name': '\u9ec4' }, { 'code': '2', 'name': '\u767d' }, { 'code': '3', 'name': '\u9ed1' }, { 'code': '4', 'name': '\u68d5' }, { 'code': '0', 'name': '\u672a\u77e5' }],
    sexInfo: [{ 'code': '0', 'name': '\u672a\u77e5', 'englishName': 'uncertain' }, { 'code': '1', 'name': '\u7537', 'englishName': 'male' }, { 'code': '2', 'name': '\u5973', 'englishName': 'female' }],
    cardSexInfo: [{ 'code': '0', 'name': '\u672a\u77e5', 'englishName': 'uncertain' }, { 'code': '1', 'name': '\u7537', 'englishName': 'male' }, { 'code': '2', 'name': '\u5973', 'englishName': 'female' }],
    shapeInfo: [{ 'code': '1', 'name': '\u5706\u8138' }, { 'code': '2', 'name': '\u957f\u65b9\u5f62\u8138' }, { 'code': '3', 'name': '\u6b63\u65b9\u5f62\u8138' }, { 'code': '4', 'name': '\u9e45\u86cb\u8138' }, { 'code': '5', 'name': '\u74dc\u5b50\u8138' }, { 'code': '0', 'name': '\u672a\u77e5' }],
    hatInfo: [{ 'code': '0', 'name': '\u672a\u77e5' }, { 'code': '1', 'name': '\u672a\u6234\u5e3d\u5b50' }, { 'code': '2', 'name': '\u6234\u5e3d\u5b50' }, { 'code': '3', 'name': '\u8fde\u8863\u5e3d' }],
    //违法行为
    'illegalBehaviorInfo': [
        { 'code': null, 'name': '全部' },
        { 'code': 2004, 'name': '违章变道' },
        { 'code': 6000, 'name': '机动车违反禁令标志指示 ' },
        { 'code': 2001, 'name': '不按导向车道行驶 ' },
        { 'code': 3004, 'name': '交通抛洒物事件' },
        { 'code': 2012, 'name': '黄网格违章停车 ' },
        { 'code': 5001, 'name': '遮挡车牌 ' },
        { 'code': 3003, 'name': '吸烟 ' },
        { 'code': 1002, 'name': '闯黄灯' },
        { 'code': 2011, 'name': '违章倒车 ' },
        { 'code': 2010, 'name': '有车占道' },
        { 'code': 2009, 'name': '黄牌车占道' },
        { 'code': 2008, 'name': '违章停车' },
        { 'code': 4001, 'name': '超低速' },
        { 'code': 3002, 'name': '未系安全带' },
        { 'code': 2006, 'name': '占用公交车道' },
        { 'code': 3001, 'name': '接打电话' },
        { 'code': 2005, 'name': '压黄线' },
        { 'code': 2003, 'name': '机动车占用非机动车道' },
        { 'code': 2013, 'name': '逆行' },
        { 'code': 2002, 'name': '压线' },
        { 'code': 1001, 'name': '闯红灯' }
    ],
    //车辆颜色
    'colorInfo': [
        { 'code': null, 'name': '全部' },
        { 'code': 1, 'name': '黑色' },
        { 'code': 2, 'name': '蓝色' },
        { 'code': 3, 'name': '棕色' },
        { 'code': 4, 'name': '绿色' },
        { 'code': 5, 'name': '灰色' },
        { 'code': 6, 'name': '白色' },
        { 'code': 7, 'name': '红色' },
        { 'code': 8, 'name': '黄色' },
        { 'code': 9, 'name': '粉色' },
        { 'code': 10, 'name': '紫色' },
        { 'code': 11, 'name': '青色' },
        { 'code': 12, 'name': '深灰色' },
        { 'code': 13, 'name': '金色' }
    ],
    'carType': [],
    //号牌种类
    'plateType': [
        { 'code': 1, 'name': '大型汽车号牌' },
        { 'code': 2, 'name': '小型汽车号牌' },
        { 'code': 3, 'name': '使馆汽车号牌' },
        { 'code': 4, 'name': '领馆汽车号牌' },
        { 'code': 5, 'name': '境外汽车号牌' },
        { 'code': 6, 'name': '外籍汽车号牌' },
        { 'code': 7, 'name': '两、三轮摩托车号牌' },
        { 'code': 8, 'name': '轻便摩托车号牌' },
        { 'code': 9, 'name': '使馆摩托车号牌' },
        { 'code': 10, 'name': '领馆摩托车号牌' },
        { 'code': 11, 'name': '境外摩托车号牌' },
        { 'code': 12, 'name': '外籍摩托车号牌' },
        { 'code': 13, 'name': '农用运输车号牌' },
        { 'code': 14, 'name': '拖拉机号牌' },
        { 'code': 15, 'name': '挂车号牌' },
        { 'code': 16, 'name': '教练汽车号牌' },
        { 'code': 17, 'name': '教练摩托车号牌' },
        { 'code': 18, 'name': '试验汽车号牌' },
        { 'code': 19, 'name': '试验摩托车号牌' },
        { 'code': 20, 'name': '临时人境汽车号牌' },
        { 'code': 21, 'name': '临时人境摩托车号牌' },
        { 'code': 22, 'name': '临时行驶车号牌' },
        { 'code': 23, 'name': '警用汽车号牌' },
        { 'code': 24, 'name': '警用摩托号牌' },
        { 'code': 26, 'name': '香港入出境车' },
        { 'code': 27, 'name': '澳门入出境车' },
        { 'code': 31, 'name': '武警号牌' },
        { 'code': 32, 'name': '军队号牌' },
        { 'code': 98, 'name': '无牌车' },
        { 'code': 99, 'name': '其他号牌' }
        // { 'code': 6000, 'name': '机动车违反禁令标志指示 ' },
        // { 'code': 4001, 'name': '超低速' },
        // { 'code': 3002, 'name': '未系安全带' },
        // { 'code': 3001, 'name': '接打电话' },
        // { 'code': 2006, 'name': '占用公交车道' },
        // { 'code': 2005, 'name': '压黄线' },
        // { 'code': 2004, 'name': '违章变道' },
        // { 'code': 2003, 'name': '机动车占用非机动车道' },
        // { 'code': 2013, 'name': '逆行' },
        // { 'code': 2002, 'name': '压线' },
        // { 'code': 2001, 'name': '不按导向车道行驶 ' },
        // { 'code': 1001, 'name': '闯红灯' }
    ],
    'vehicleDirection': [
        { 'code': 1, 'name': '西向东' },
        { 'code': 2, 'name': '东向西' },
        { 'code': 3, 'name': '北向南' },
        { 'code': 4, 'name': '南向北' },
        { 'code': 5, 'name': '西南到东北' },
        { 'code': 6, 'name': '东北到西南' },
        { 'code': 7, 'name': '西北到东南' },
        { 'code': 8, 'name': '东南到西北' },
        { 'code': 9, 'name': '其他' }
    ],
    // 号牌颜色 车牌颜色
    'carplateColorInfo': [
        { 'code': null, 'name': '全部' },
        { 'code': 1, 'name': '白色' },
        { 'code': 2, 'name': '黄色' },
        { 'code': 3, 'name': '蓝色' },
        { 'code': 4, 'name': '黑色' },
        { 'code': 5, 'name': '绿色' },
        { 'code': 6, 'name': '黄绿色' }
    ]
};
